### This is supposed to be generated by n8n google sheet mapping columns

ami_id         = "ami-00839deb72faa8a04"
instance_type  = "t3.micro"
region         = "ap-southeast-2"
#vpc_cidr       = "172.31.0.0/16"
#subnet_cidr    = "172.31.0.0/20"
#ssh_key_name     = "tftest"
existing_vpc_name = "appstech-vpc"
